package com.maviinamane.delivery;
import java.math.BigDecimal; import java.time.Instant; import java.util.List; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.web.server.ResponseStatusException;
@Service public class DeliveryChargeService {
 public static final String DISTANCE="DISTANCE",WEIGHT="WEIGHT"; private final DeliveryChargeConfigRepository repository; public DeliveryChargeService(DeliveryChargeConfigRepository r){repository=r;}
 public List<DeliveryChargeConfig> all(String type){return type==null?repository.findAll():repository.findByTypeOrderByMinValueAsc(type.toUpperCase());}
 public DeliveryChargeConfig save(DeliveryChargeConfig v){validate(v);v.setType(v.getType().toUpperCase());v.setUpdatedAt(Instant.now());if(v.getCreatedAt()==null)v.setCreatedAt(Instant.now());return repository.save(v);} public void delete(String id){repository.deleteById(id);}
 public Quote calculate(BigDecimal distanceKm,BigDecimal weightKg){if(distanceKm==null||distanceKm.signum()<0)bad("distanceKm must be zero or greater");if(weightKg==null||weightKg.signum()<0)bad("weightKg must be zero or greater");var d=matching(DISTANCE,distanceKm).getCharge();var w=matching(WEIGHT,weightKg).getCharge();return new Quote(distanceKm,weightKg,d,w,d.add(w));}
 private DeliveryChargeConfig matching(String type,BigDecimal value){return repository.findByTypeAndActiveTrueOrderByMinValueAsc(type).stream().filter(s->value.compareTo(s.getMinValue())>=0&&(s.getMaxValue()==null||value.compareTo(s.getMaxValue())<=0)).findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"No active "+type.toLowerCase()+" slab matches "+value));}
 private void validate(DeliveryChargeConfig v){if(v.getType()==null||(!DISTANCE.equalsIgnoreCase(v.getType())&&!WEIGHT.equalsIgnoreCase(v.getType())))bad("type must be DISTANCE or WEIGHT");if(v.getMinValue()==null||v.getMinValue().signum()<0)bad("Minimum value cannot be negative");if(v.getMaxValue()!=null&&v.getMaxValue().compareTo(v.getMinValue())<=0)bad("Maximum value must be greater than minimum");if(v.getCharge()==null||v.getCharge().signum()<0)bad("Charge cannot be negative");for(var o:repository.findByTypeOrderByMinValueAsc(v.getType().toUpperCase()).stream().filter(s->!java.util.Objects.equals(s.getId(),v.getId())).toList()){boolean overlap=v.getMaxValue()==null?(o.getMaxValue()==null||o.getMaxValue().compareTo(v.getMinValue())>0):o.getMinValue().compareTo(v.getMaxValue())<0&&(o.getMaxValue()==null||o.getMaxValue().compareTo(v.getMinValue())>0);if(overlap)bad("Slab overlaps an existing range");}}
 private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} public record Quote(BigDecimal distanceKm,BigDecimal weightKg,BigDecimal distanceCharge,BigDecimal weightCharge,BigDecimal deliveryCharge){}
}
